config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'static#index'

  get 'about' => 'static#about'
  get 'contact' => 'static#contact'
  get 'staff-login' => 'static#staff_login'
  get 'dashboards/supervisor/new-staff' => 'static#new_staff'

  get 'dashboards/tenant', controller: 'dashboards', action: 'tenant'
  get 'dashboards/assistant', controller: 'dashboards', action: 'assistant'
  get 'dashboards/supervisor', controller: 'dashboards', action: 'supervisor'
  get 'dashboards/manager', controller: 'dashboards', action: 'manager'
  get 'dashboards/tenant/pending_complaints', controller: 'dashboards', action: 'pending_complaints'

  authenticate :user do
    resources :testimonials, only: [:new, :create, :edit, :update, :destroy]
    resources :rentals
    resources :complaints
    resources :dashboards, only: [:index ]
  end

  resources :testimonials
  resources :rental_invoices

  resources :tenants

  resources :rentals do
    resources :complaints, module: :rentals
    resources :rental_invoices
    resources :tenant_family_members
    resources :tenant_autos
  end

  resources :apartments do
    resources :complaints, module: :apartments
  end

  resources :staffs
  resources :apartment_types

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  validates :first_name, presence: true

  enum gender: { male: 0, female: 1 }
  enum position: { customer_service: 0, assistant: 2, manager: 3, supervisor: 4 }

  belongs_to :user
  has_many :rentals

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:first_name, :last_name, :position, :gender, :dob, :salary, :username, :password)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_for @staff, class: "form" do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :position %><br>
    <%= f.number_field :position, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :gender %><br>
    <%= f.number_field :gender, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :dob %><br>
    <%= f.date_select :dob, start_year: 1900, end_year: Date.today.year, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :salary %><br>
    <%= f.number_field :salary, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<h1>Listing Staffs</h1>

<table class="table table-hover table-condensed table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Position</th>
      <th>Gender</th>
      <th>Dob</th>
      <th>Salary</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.first_name %></td>
        <td><%= staff.last_name %></td>
        <td><%= staff.position.titlecase %></td>
        <td><%= staff.gender.titlecase %></td>
        <td><%= staff.dob %></td>
        <td><%= number_to_currency staff.salary %></td>
        <td><%= staff.user.username %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<h3>Staff</h3>

<%= render partial: "staffs/shared/staff", locals: { staff: @staff } %>

<h3>Rentals Created</h3>
<%= render partial: "rentals/shared/simple_rentals", locals: { rentals: @staff.rentals } %>

<h3>Complaints Made</h3>
<%= render partial: "complaints/shared/complaints", locals: { complaints: Complaint.where(user: Staff.find_by_id(230).user) } %>
<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>