config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'static#index'

  get 'about' => 'static#about'
  get 'contact' => 'static#contact'
  get 'staff-login' => 'static#staff_login'
  get 'dashboards/supervisor/new-staff' => 'static#new_staff'

  get 'dashboards/tenant', controller: 'dashboards', action: 'tenant'
  get 'dashboards/assistant', controller: 'dashboards', action: 'assistant'
  get 'dashboards/supervisor', controller: 'dashboards', action: 'supervisor'
  get 'dashboards/manager', controller: 'dashboards', action: 'manager'
  get 'dashboards/tenant/pending_complaints', controller: 'dashboards', action: 'pending_complaints'

  authenticate :user do
    resources :testimonials, only: [:new, :create, :edit, :update, :destroy]
    resources :rentals
    resources :complaints
    resources :dashboards, only: [:index ]
  end

  resources :testimonials
  resources :rental_invoices

  resources :tenants

  resources :rentals do
    resources :complaints, module: :rentals
    resources :rental_invoices
    resources :tenant_family_members
    resources :tenant_autos
  end

  resources :apartments do
    resources :complaints, module: :apartments
  end

  resources :staffs
  resources :apartment_types

end

app/models/rental_invoice.rb
class RentalInvoice < ActiveRecord::Base
  enum card_type: { visa: 0, master_card: 1, discover: 2}
  belongs_to :rental
  before_save :validate_payment
  before_save :set_default_dates
  scope :paid, -> { where(is_paid: true) }
  scope :unpaid, -> { where("is_paid is NULL or false") }
  scope :on_month, -> (month) { where( 'extract(month from invoice_date) = ?', month) }
  scope :on_year, -> (year) { where( 'extract(year from invoice_date) = ?', year) }

  def paid?
    if self.is_paid.nil? || self.is_paid == false
      return false
    else
      return true
    end
  end

  def status
    paid? ? "paid" : "unpaid"
  end
  private
  def validate_payment
    if self.cc_amount_charged == self.amount
      self.is_paid = true
    end
  end

  def set_default_dates
    self.invoice_date = Date.today unless !self.invoice_date.nil?
    true
  end

end

app/controllers/rental_invoices_controller.rb
class RentalInvoicesController < ApplicationController
  before_action :set_rental_invoice, only: [:show, :edit, :update, :destroy]

  # GET /rental_invoices
  # GET /rental_invoices.json
  def index
    @rental_invoices = RentalInvoice.all
  end

  # GET /rental_invoices/1
  # GET /rental_invoices/1.json
  def show
  end

  # GET /rental_invoices/new
  def new
    @rental_invoice = RentalInvoice.new
  end

  # GET /rental_invoices/1/edit
  def edit
  end

  # POST /rental_invoices
  # POST /rental_invoices.json
  def create
    @rental_invoice = RentalInvoice.new(rental_invoice_params)

    respond_to do |format|
      if @rental_invoice.save
        format.html { redirect_to @rental_invoice, notice: 'Rental invoice was successfully created.' }
        format.json { render :show, status: :created, location: @rental_invoice }
      else
        format.html { render :new }
        format.json { render json: @rental_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rental_invoices/1
  # PATCH/PUT /rental_invoices/1.json
  def update
    @rental_invoice.cc_amount_charged = @rental_invoice.amount
    respond_to do |format|
      if @rental_invoice.update(rental_invoice_params)
        format.html { redirect_to @rental_invoice, notice: 'Rental invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental_invoice }
      else
        format.html { render :edit }
        format.json { render json: @rental_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rental_invoices/1
  # DELETE /rental_invoices/1.json
  def destroy
    @rental_invoice.destroy
    respond_to do |format|
      format.html { redirect_to rental_invoices_url, notice: 'Rental invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental_invoice
      @rental_invoice = RentalInvoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_invoice_params
      params.require(:rental_invoice).permit(:invoice_date, :cc_number, :cc_type, :cc_expiration_date, :cc_amount_charged)
    end
end

app/helpers/rental_invoices_helper.rb
module RentalInvoicesHelper
  def status_button(rental_invoice)
    html_classes = "label label-"

    if rental_invoice.paid?
      html_classes += "success"
      label = "Paid"
    elsif rental_invoice.invoice_date < Date.today
      label = "Overdue"
      html_classes += "danger"
    else
      label = "DUE Soon"
      html_classes += "warning"
    end

      button = "<span class='#{html_classes}'>#{label}</span>"
  end

  def status_row_class(rental_invoice)
    html_classes = ""

    if rental_invoice.paid?
      html_classes += "success"
    elsif rental_invoice.invoice_date < Date.today
      html_classes += "danger"
    else
      html_classes += "warning"
    end
  end

  def status_text(rental_invoice)
    if rental_invoice.paid?
      ""
    elsif rental_invoice.invoice_date < Date.today
      "Overdue"
    else
      "Due Soon"
    end
  end

  def rental_invoice_action_text(rental_invoice)
    if rental_invoice.paid?
      "View Receipt"
    else
      "Pay Invoice"
    end
  end

  def rental_invoice_action(rental_invoice)
    if rental_invoice.paid?
      "Payment Record"
    else
      "Pay Invoice"
    end
  end

  def display_rental_status(rental_invoice)
    "#{rental_invoice.status.titlecase} #{status_text(rental_invoice)}"
  end
end

app/views/rental_invoices/_form.html.erb
<%= form_for(@rental_invoice) do |f| %>
  <% if @rental_invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental_invoice.errors.count, "error") %> prohibited this rental_invoice from being saved:</h2>

      <ul>
      <% @rental_invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :invoice_date %><br>
    <%= f.date_select :invoice_date %>
  </div>
  <div class="field">
    <%= f.label :cc_number %><br>
    <%= f.text_field :cc_number %>
  </div>
  <div class="field">
    <%= f.label :cc_type %><br>
    <%= f.text_field :cc_type %>
  </div>
  <div class="field">
    <%= f.label :cc_expiration_date %><br>
    <%= f.text_field :cc_expiration_date %>
  </div>
  <div class="field">
    <%= f.label :cc_amount_charged %><br>
    <%= f.text_field :cc_amount_charged %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rental_invoices/edit.html.erb
<h1>Editing Rental Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @rental_invoice %> |
<%= link_to 'Back', rental_invoices_path %>

app/views/rental_invoices/index.html.erb
<div class="col-md-12">
  <h3>Rental Invoices</h3>
</div>
<div class="col-md-12">
  <%= render partial: "rental_invoices/shared/simple_rental_invoices", locals: { rental_invoices: @rental_invoices.order(invoice_date: :desc) } %>
</div>

<%= link_to 'New Rental invoice', new_rental_invoice_path %>

app/views/rental_invoices/new.html.erb
<h1>New Rental Invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', rental_invoices_path %>

app/views/rental_invoices/show.html.erb
<div class="row">
  <div class="col-md-12">

    <% if @rental_invoice.paid? %>
    <h2 class="alert alert-success">Rental Invoice Receipt</h2>
    <% end %>
  </div>
  <div class="col-md-6">
    <h2>Rental Invoice</h2>
    <h4>ID: <%= @rental_invoice.id %></h4>
    <h4>Invoice Status <%= raw status_button(@rental_invoice) %></h4>
    <h4>Invoice Number: <%= @rental_invoice.number %></h4>
    <h4>Invoice Amount: <%= number_to_currency @rental_invoice.amount %></h4>
    <h4>Invoice Date: <%= @rental_invoice.invoice_date %></h4>
    <% if !@rental_invoice.note.nil? %>
    <p>Note: <%= @rental_invoice.note %></p>
    <% end %>
  </div>
  <div class="col-md-6">
    <h2><%= rental_invoice_action(@rental_invoice) %></h2>
    <% if !@rental_invoice.paid? %>
    <%= render partial: "rental_invoices/shared/form", locals: { rental_invoice: @rental_invoice } %>
    <% else %>

    <h5><strong>CC Number:</strong> <%= @rental_invoice.cc_number %></h5>
    <h5><strong>CC Type:</strong> <%= @rental_invoice.cc_type.titlecase %></h5>
    <h5><strong>CC Expiration Date:</strong> <%= @rental_invoice.cc_expiration_date %></h5>
    <h5><strong>CC Amount Charged:</strong> <%= number_to_currency @rental_invoice.cc_amount_charged %></h5>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-6">
    <%= render partial: "tenants/shared/tenant", locals: { tenant: @rental_invoice.rental.tenant } %>
  </div>

  <div class="col-md-6">
    <%= render partial: "rentals/shared/rental", locals: { rental: @rental_invoice.rental } %>
  </div>
</div>



<p>

</p>

<%= link_to 'Edit', edit_rental_invoice_path(@rental_invoice) %> |
<%= link_to 'Back', rental_invoices_path %>