config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'static#index'

  get 'about' => 'static#about'
  get 'contact' => 'static#contact'
  get 'staff-login' => 'static#staff_login'
  get 'dashboards/supervisor/new-staff' => 'static#new_staff'

  get 'dashboards/tenant', controller: 'dashboards', action: 'tenant'
  get 'dashboards/assistant', controller: 'dashboards', action: 'assistant'
  get 'dashboards/supervisor', controller: 'dashboards', action: 'supervisor'
  get 'dashboards/manager', controller: 'dashboards', action: 'manager'
  get 'dashboards/tenant/pending_complaints', controller: 'dashboards', action: 'pending_complaints'

  authenticate :user do
    resources :testimonials, only: [:new, :create, :edit, :update, :destroy]
    resources :rentals
    resources :complaints
    resources :dashboards, only: [:index ]
  end

  resources :testimonials
  resources :rental_invoices

  resources :tenants

  resources :rentals do
    resources :complaints, module: :rentals
    resources :rental_invoices
    resources :tenant_family_members
    resources :tenant_autos
  end

  resources :apartments do
    resources :complaints, module: :apartments
  end

  resources :staffs
  resources :apartment_types

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  #enum apartment_type: { zero_bedroom: 0, one_bedroom: 1, two_bedroom: 2, three_bedroom: 3 }
  enum status: { vacant: 0, rented: 1 }
  has_many :rentals
  has_many :tenants, through: :rentals
  has_many :complaints, as: :complaintable

  scope :vacant, -> { where( status: self.statuses[:vacant]) }
  scope :rented, -> { where( status: self.statuses[:rented]) }

  belongs_to :apartment_type
end

app/models/apartment_type.rb
class ApartmentType < ActiveRecord::Base
  has_many :apartments
  
end

app/controllers/apartments/complaints_controller.rb
class Apartments::ComplaintsController < ComplaintsController
  before_action :set_complaintable

  private

  def set_complaintable
    logger.debug "Complaint Controller: Setting Complaint"
    @complaintable = Apartment.find(params[:apartment_id])

    logger.debug "Complaint Controller: Set #{@complaintable}"
  end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:apartment_type_id, :status)
    end

end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= form_for @apartment, class: "form" do |f| %>
  <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% @apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :apartment_id, "Apartment ID" %>
    <%= @apartment.id %>
  </div>

  <div class="form-group">
    <%= f.label :apartment_type, "Apartment Type" %><br>
    <%= f.collection_select :apartment_type_id, ApartmentType.all, :id, :name, {}, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :status, "Status" %><br>
    <%= f.collection_select :status, Apartment.statuses.map { |s| [s.first, s.first.titlecase ] }, :first, :last, {}, { class: "form-control" } %>
  </div>
  <div class="actions">
    <%= f.submit "Update Apartment", class: "form-control" %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>Apartments Overview</h3>
    <h4>Total Apts: <%= @apartments.count %></h4>
  </div>

  <div class="col-md-6">
    <h3>Vacant Apartments</h3>
    <%= render partial: "apartments/shared/simple_apartments", locals: { apartments: @apartments.vacant } %>
  </div>

  <div class="col-md-12">
    <h3>Rented Apartments</h3>
    <%= render partial: "apartments/shared/simple_apartments", locals: { apartments: @apartments.rented } %>
  </div>
</div>

<%= link_to 'New Apartment', new_apartment_path %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<span><strong>Apartment ID:</strong> <%= @apartment.id %></span>
<span><strong>Apartment Type:</strong><%= @apartment.apartment_type.name %></span><br/>
<span><strong>Status:</strong><%= @apartment.status %>
</span>

<div class="row">
  <div class="col-md-12">
    <h3>Pending Complaints for Apartment</h3>
  </div>
  <div class="col-md-12">
    <%= render partial: "complaints/shared/associated_complaints", locals: {complaintable: @apartment} %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h3>File A Complaint</h3>
  </div>
    <%= render partial: "complaints/shared/form", locals: {complaintable: @apartment} %>
</div>


<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>