config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'static#index'

  get 'about' => 'static#about'
  get 'contact' => 'static#contact'
  get 'staff-login' => 'static#staff_login'
  get 'dashboards/supervisor/new-staff' => 'static#new_staff'

  get 'dashboards/tenant', controller: 'dashboards', action: 'tenant'
  get 'dashboards/assistant', controller: 'dashboards', action: 'assistant'
  get 'dashboards/supervisor', controller: 'dashboards', action: 'supervisor'
  get 'dashboards/manager', controller: 'dashboards', action: 'manager'
  get 'dashboards/tenant/pending_complaints', controller: 'dashboards', action: 'pending_complaints'

  authenticate :user do
    resources :testimonials, only: [:new, :create, :edit, :update, :destroy]
    resources :rentals
    resources :complaints
    resources :dashboards, only: [:index ]
  end

  resources :testimonials
  resources :rental_invoices

  resources :tenants

  resources :rentals do
    resources :complaints, module: :rentals
    resources :rental_invoices
    resources :tenant_family_members
    resources :tenant_autos
  end

  resources :apartments do
    resources :complaints, module: :apartments
  end

  resources :staffs
  resources :apartment_types

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :tenant
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]
  before_action :force_profile, except: [:index]
  skip_before_filter :authenticate_user!

  # GET /testimonials
  # GET /testimonials.json
  def index
    if params[:keywords].present?
      @keywords = params[:keywords]
      testimonial_search_term = SearchTerm.new(@keywords, { search_types: ['content'] })
      @testimonials = Testimonial.where(
          testimonial_search_term.where_clause,
          testimonial_search_term.where_args).
        order(testimonial_search_term.order)

      logger.debug testimonial_search_term.where_clause
      logger.debug testimonial_search_term.where_args

      logger.debug "Testing"
    else
      @testimonials = Testimonial.all
    end
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)
    @testimonial.tenant = current_user.tenant
    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to tenant_path(current_user.tenant), notice: 'Thank you for your feedback!' }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:date_entered, :content)
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= form_for @testimonial, html: { class: 'form-horizontal' } do |f| %>
  <% if @testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
      <% @testimonial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Save Testimonial', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing Testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<!-- Start Jumbotron: Testimonial Call To Action -->
<% if user_signed_in? && !current_user.tenant.nil? && !current_user.tenant.rentals.nil? %>
<div class="row add-testimonial call-to-action jumbotron">
	<h3>Hey there!</h3>
	<p>Satisfied with your apartment and management so far, leave a testimonial!</p>
	<%= link_to 'Leave Testimonial &rsaquo;'.html_safe , new_testimonial_path, class: "btn btn-large btn-success", style: "color: white;" %>
</div>
<% end %>
<!-- End Jumbotron: Testimonial Call To Action -->

<div class="row testimonials-search">
	<%= render partial: 'testimonials/shared/search_bar' %>
</div>

<div class="featured-testimonials row">
	<div class="col-xs-12 col-md-12">
		<% if params[:keywords].nil? %>
		<h3>Featured Testimonials</h3>
		<% else %>
		<h3>Testimonials Search Results</h3>
		<% end %>
	</div>
	<% if params[:keywords].nil? %>
	<%= render partial: 'testimonials/shared/featured_testimonial', locals: { testimonial: nil } %>
	<% end %>

	<% @testimonials.each do |testimonial| %>
		<% if !@testimonials.blank? %>
			<!-- Start Featured Testimonial Item -->
			<div class="featured-testimonial-item testimonial-item col-md-6">
			  <div class="featured-image col-xs-4" style="padding: 0;">
			    <img alt="FeaturedTestimonial" src="<%= image_path 'like_image.jpg' %>" style="width: 100%;">
			  </div>
			  <div class="col-xs-8">
			    <blockquote>
			      <span class="primary-quote"><%= testimonial.content %></span>
			      <footer>
			        <%= testimonial.tenant.full_name %>
			      </footer>
			    </blockquote>
					<% if user_signed_in? && current_user.role.name == "supervisor" %>
					<div class="testimonial-admin-options">
						<%= link_to 'Edit', edit_testimonial_path(testimonial), class: 'btn btn-sm btn-primary', style: "color: #FFF;" %>
						<%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-primary', style: "color: #FFF;" %>
					</div>
					<% end %>
			  </div>
			</div>
			<!-- End Featured Testimonial Item -->
		<% end %>
	<% end %>

	<% if !params[:keywords].nil? && @testimonials.empty? %>
	<div class="col-md-12">
		<div class="well well-lg">
			<h3 class="text-center">No Tesitmonials Found for <%= params[:keywords] %></h3>
		</div>
	</div>

	<% end %>
</div>



<%= render "static/shared/featured_apartments" %>

app/views/testimonials/new.html.erb
<h1>New Testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p>
  <%= @testimonial.content %>
</p>

<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>